config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  get '/sign_in', to: 'sessions#sign_in', as: 'sign_in'
  post '/sign_in', to: 'sessions#create'
  get '/sign_out', to: 'sessions#sign_out', as: 'sign_out'
  delete '/sign_out', to: 'sessions#destroy'

  root 'cheeses#index'

  resources :cheeses
  resources :users
  resources :likes

end

app/models/cheese.rb
class Cheese < ActiveRecord::Base
  belongs_to :users
  has_many :likes
  has_many :users, :through => :likes, source: :user
  accepts_nested_attributes_for :users

  def likes_count
    likes.count
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :cheese
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :cheeses, :through => :likes, source: :cheese
  accepts_nested_attributes_for :cheeses
  has_many :likes
  has_secure_password

  def liked_count
    likes.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user # Make every action authenticated

  def log_in(user)
   session[:user_id] = user.id
  end

  def signed_in?
    session[:user_id].present?
  end
  helper_method :signed_in? # Make this method available on the view as a helper

  def current_user
    return if session[:user_id].nil?
    @current_user ||= User.find(session[:user_id]) # Return the current_user
  end
  helper_method :current_user # Make this method available on the view as a helper

  def authenticate_user
    if session[:user_id].nil?
      flash[:alert] = "Must be signed in"
      redirect_to sign_in_path
    end
  end
end

app/controllers/cheeses_controller.rb
class CheesesController < ApplicationController
  before_action :set_cheese, only: [:show, :edit, :update, :destroy]
   def index
     @cheeses = Cheese.all.sort_by { |cheese| cheese.likes_count }.reverse!
   end

   def show
     @cheese = Cheese.find(params[:id])
     @users = @cheese.users
   end

   def new
     @cheese = Cheese.new
   end

   def create
     @cheese = Cheese.new(cheese_params)

     respond_to do |format|
       if @cheese.save
         format.html { redirect_to @cheese, notice: 'Cheese was successfully created.' }
         format.json { render :show, status: :created, location: @cheese }
       else
         format.html { render :new }
         format.json { render json: @cheese.errors, status: :unprocessable_entity }
       end
     end
   end

   private

  def set_cheese
     @cheese = Cheese.find(params[:id])
  end

  def cheese_params
    params.require(:cheese).permit(:name)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user

  def sign_in
  end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      log_in user
      flash[:notice] = "Successfully signed in!"
      redirect_to root_path
    else
      flash[:alert] = "Username and password did not match any records"
      render :sign_in
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Signed out!"
    redirect_to root_path
  end

  def sign_out
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @cheeses = @user.cheeses
  end


  def new
    @user = User.new
  end


  def edit
  end


  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        session[:user_id] = @user.id
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    set_user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, cheese_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cheeses_helper.rb
module CheesesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
   session[:user_id] = user.id
  end

 def current_user
   @current_user ||= User.find_by(id: session[:user_id])
 end

 def logged_in?
   !current_user.nil?
 end

 def log_out
   session.delete(:user_id)
   @current_user = nil
 end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cheeses/index.html.erb
<div class="container">
  <div>
    <p id="notice"><%= notice %></p>
  </div>

  <% if signed_in? %>
  <h3>Hello <%=link_to current_user.username, user_path(current_user.id) %>!</h3>
  <%end %>

  <h1>List of Cheeses </h1>

<table class="table table-striped">
 <thead class="thead-inverse">
   <tr>
     <th>Name:</th>
     <th colspan="3"></th>
   </tr>
 </thead>

 <tbody>
   <% @cheeses.each do |cheese| %>
     <tr>
       <td><%= cheese.name %></td>
       <td><%= cheese.likes_count %></td>
       <td><%= link_to 'Show', cheese %></td>
     </tr>
   <% end %>
 </tbody>
</table>

<br>

<%= link_to 'New Cheese', new_cheese_path, class: "btn btn-default" %>
</div>

app/views/cheeses/new.html.erb
<div class="container">
  <h1>New Cheese</h1>
    <div class = "col-md-6">
  <%= form_for(@cheese) do |f| %>
    <% if @cheese.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@cheese.errors.count, "error") %> prohibited this cheese from being saved:</h2>

        <ul>
        <% @cheese.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_area :name %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
  </div>
  </div>


  <%= link_to 'Back cheeses', cheeses_path, class: "btn btn-default navbar-btn"%>
</div>

app/views/cheeses/show.html.erb
</br>
</br>
</br>
</br>


<p>
 <strong>Name:</strong>
 <%= @cheese.name %>
 <ol>
 <% @cheese.users.each do |user| %>
   <p><%= user.username %></p>
 <% end %>
 </ol>
</p>

<%= link_to 'Back', cheeses_path, class: "btn btn-default"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReactCheese</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

  <% if signed_in? %>
    <%= react_component("NavBar") %>
  <% else %>
    <%= react_component("LoggedOutNavBar") %>
  <% end %>

<%= yield %>
</div>
</body>
</html>

app/views/likes/index.html.erb
<%= simple_form_for current_user do |f| %>
  <%= f.association :cheeses, as: :check_boxes,collection: Cheese.all %>
  <%= f.submit 'Save Favorite Cheeses' %>
<% end %>

app/views/users/_form.html.erb
<div class="col-md-6">
  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :username %><br>
      <%= f.text_field :username %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">

    <div class="row">
      <p id="notice"><%= notice %></p>

    <% if signed_in? %>
      <h1>Hello <%=link_to current_user.username, user_path(current_user.id) %>!</h1>
      <%end %>

  <h3>List of Users</h3>
  <table class="table table-striped">
    <thead class="thead-inverse">
      <tr>
        <th>Name</th>
        <th>Likes</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.username %></td>

          <td><%= link_to 'Show', user %></td>
        </tr>
      <% end %>

    </tbody>
  </table>

<br>

</div>

app/views/users/new.html.erb
<div class="container">
  <h1>New User</h1>

  <%= render 'form' %>

  <%= link_to 'Back', users_path, class: "btn btn-default" %>
</div>

app/views/users/show.html.erb
</br>
</br>
</br>
</br>

<table class="table table-striped">
  <thead class="thead-inverse">
    <tr>
      <th> <%= @user.username %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @cheeses.each do |cheese| %>
      <tr>
        <td><%= cheese.name %></td>

        <td> <%= link_to 'Show', cheese %></td>
      </tr>
    <% end %>

  </tbody>
</table>


<%= link_to 'Back', users_path, class: "btn btn-default" %>